name: game_center
description: 'App to manage your games and performance'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  handy_window: ^0.4.0
  intl: ^0.19.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  ubuntu_localizations: ^0.4.0
  ubuntu_logger: ^0.1.1
  ubuntu_service: ^0.3.2
  vdf: ^1.1.0
  watcher: ^1.1.0
  yaru: ^4.1.0
  yaru_window: ^0.2.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.4.2
  ubuntu_lints: ^0.4.0
  yaru_test: ^0.1.6

flutter:
  fonts:
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMono-R.ttf
          weight: 400
        - asset: assets/fonts/UbuntuMono-RI.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/UbuntuMono-B.ttf
          weight: 700
        - asset: assets/fonts/UbuntuMono-BI.ttf
          weight: 700
          style: italic
  uses-material-design: true
  generate: true
