name: game-center
summary: Game Center
description: Game Center
base: core24
grade: devel
confinement: strict
version: 0.1.0

apps:
  game-center:
    command: bin/game_center
    extensions:
      - gnome
    plugs:
      - desktop
      - desktop-legacy

parts:
  flutter-git:
    plugin: nil
    source: .
    override-pull: |
      # necessary when reruns using the same container
      if [ -d "flutter" ]; then
        rm -rf "flutter"
      fi

      craftctl default
      FVM_VERSION=$(curl -s https://api.github.com/repos/leoafarias/fvm/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
      curl -L "https://github.com/leoafarias/fvm/releases/download/$FVM_VERSION/fvm-$FVM_VERSION-linux-x64.tar.gz" -o fvm.tar.gz
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp $CRAFT_PART_SRC/.fvmrc $CRAFT_PART_INSTALL

      tar xzf fvm.tar.gz
      rm fvm.tar.gz
      mv fvm $CRAFT_PART_INSTALL/fvm
      ln -s $CRAFT_PART_INSTALL/fvm/fvm $CRAFT_PART_INSTALL/usr/bin/fvm
      cd $CRAFT_PART_INSTALL
      $CRAFT_PART_INSTALL/usr/bin/fvm install

      cp -r $CRAFT_PART_INSTALL/.fvm/flutter_sdk $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $CRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - git
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ""

  game-center:
    after:
      - flutter-git
    plugin: nil
    source: .
    override-build: |
      dart pub global activate melos
      dart pub global run melos clean
      dart pub global run melos bootstrap
      cd packages/game_center
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
