name: Snap

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  snap:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: snapcore/action-build@v1
        id: snapcraft
      - uses: actions/upload-artifact@v4
        with:
          name: 'snap'
          path: ${{steps.snapcraft.outputs.snap}}
